seed: 1337
word2vec:
  hyper:
    minWordFrequency: 5
    iterations: 1
    layerSize: 300
    windowsSize: 5
  models:
    pathToModel: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier/word2vec.bin'
    pathToWordVectors: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier/wordVectors.txt'
wykop:
  postsDir: 'D:\Programowanie\deep_learning\wykop\posts'
test:
  batchSize: 50
  maxWordsInPost: 50
  epochs: 999999999
rnn:
  iterations: 1
  maxWordsInDialog: 30
  batchSize: 50
  regularization: false
  learningRate: 0.01
  l2: 1e-5
  gradientNormalizationThreshold: 1.0
  layers:
    l0:
      nout: 200
  pathToSaveModel: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier/rnn-model.bin'