seed: 1337
word2vec:
  hyper:
    minWordFrequency: 5
    iterations: 1
    layerSize: 300
    windowsSize: 5
  models:
    pathToModel: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier/word2vec.bin'
    pathToWordVectors: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier/wordVectors.txt'
wykop:
  postsDir: 'D:\Programowanie\deep_learning\wykop\posts'
test:
  batchSize: 200
  maxWordsInPost: 300
  epochs: 999999999
  suppressWarnings: true
rnn:
  iterations: 1
  maxWordsInDialog: 30
  regularization: false
  learningRate: 0.1
  l2: 1e-5
  gradientNormalizationThreshold: 1.0
  layers:
    l0:
      nout: 200
iterationListener:
  fileStatsStorage: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier\data\ui_service.bin'
  printIterations: 250
fileMultiLayerNetwork:
  dirToSave: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier\rnn-models'
  modelPrefix: 'rnn-'
  modelSuffix: '.bin'
jsonEpochResultSaver:
  dirToSave: 'D:\Programowanie\deep_learning\wykop\wykop-post-clasifier\epochs'
  modelPrefix: 'epoch-'
  modelSuffix: '.json'